.drone.yml
Dockerfile-acceptance
acceptance_tests/features/applicant-name.js
app.js
config.js
package.json
test.sh

* bumped so-acceptance to 2.0.0
* removed MemoryStore session mocking
* added redis service back to drone

Use real redis

---

app.js

This was causing an error when rendering terms and cookies pages

bugfix - include path to translations

---

apps/complaints/translations/src/en/validation.json

* changed validation message to "You can’t make a complaint on behalf of someone else without consent. If you don’t have consent, don’t use this service"

bugfix UCHV-90 - declaration validation wording

---

apps/complaints/translations/src/en/validation.json

Added validation text for "equal" which is added to all select fields by default - need to select an item from the list

Bugfix - UCHV-105 - country validation

---

apps/complaints/translations/src/en/fields.json

* removed summary text from the first field so it reads well on summary page.
This change is necessary due to a change in the confirm controller - it used to show the radio value on summary page but now shows the label.

bugfix - UCHV-121 - summary page label

---

package.json

Update to hof-bootstrap 9.3.1 to enable auto-addition of google-analytics-specific CSP directives, which means the google analytics script can load it's own js and images

update to hof-bootstrap 9.3.1

---

apps/ukvi-complaints/fields/index.js
apps/ukvi-complaints/translations/src/en/fields.json
apps/ukvi-complaints/translations/src/en/pages.json
apps/ukvi-complaints/views/error.html
hof.settings.json

Adds custom error page for when the form fails to add the data to the SQS queue
Adds max length constraints on all text fields, in accordance with the schema
So the user knows their form has failed to submit, and they can retry
So the user can't input too many characters, which would break the validation against the schema and make the form fail to submit

SD-272: Front end changes

---

apps/ukvi-complaints/schema/decs.json

What:
- Added max lengths to the city types in the decs json schema. This is V1 of the decs schema.
Why
- This will ensure the data we send to the decs caseworking system can be accepted and processed.

Add max-lengths to city type in schema

---

apps/ukvi-complaints/lib/json-converters/complaint.js
test/unit/lib/json-converters/existing.spec.js

The existing complaint route was throwing an error because the complaint data formatting functionality was expecting reporter details when they are not required if the user has entered an existing complaint number.
I have moved the reporter details to an optional field only if the 'acting-as-agent' field present with the form data.

HOF-7-existing-complaint-bug

---

apps/ukvi-complaints/behaviours/send-to-sqs.js
apps/ukvi-complaints/lib/utils.js
test/unit/lib/behaviours/send-to-sqs.spec.js
test/unit/lib/utils.spec.js

Added more detailed logging on both successful and failed complaints submissions. The complaint ID, complaint details and a descriptive message is now logged out. This should make it easier to find and identify any issues if a complaint fails to submit.

Hof 6 improve logging

---

config.js

Change to use on/off toggle instead of true false as kubernetes config map does not work with boolean values

HOF-9-on/off-decs-integration-toggle

---

apps/ukvi-complaints/index.js
hof.settings.json
index.js

Update title in cookie banner to match the service title
Update app to ensure locals are available on /cookies and /terms-and-conditions pages so the service title is shown in the cookie banner

SD-235: Fix cookie banner

---

config.js

Update config file to change fallback transport option from 'stub' to 'ses'
The kube files do not include any email transport settings, meaning dev is using the fallback option

SD-994: Update config file to remove stub as transport option

---

apps/ukvi-complaints/fields/index.js

Unhide VAC country field by removing the 'js-hidden' class

Unhide VAC Country field

---

apps/ukvi-complaints/views/when-applied.html

Adds backlink to /when-applied page
Adds custom layout for the page which includes the backlin. Did it this way because the page isn't a part of the actual journey, it's redirected from another page through a hyperlink.

Add backlink to /when-applied page

---

apps/ukvi-complaints/views/content/en/application-technical.md
apps/ukvi-complaints/views/content/en/complain-about-ukvi-when.md
apps/ukvi-complaints/views/content/en/complain-about-ukvi.md
apps/ukvi-complaints/views/content/en/contact-ukvi-inside.md
apps/ukvi-complaints/views/content/en/contact-ukvi-outside.md
apps/ukvi-complaints/views/content/en/delayed-outside.md
apps/ukvi-complaints/views/content/en/negative-outcome.md
apps/ukvi-complaints/views/content/en/positive-outcome-inside.md
apps/ukvi-complaints/views/content/en/positive-outcome-outside.md
apps/ukvi-complaints/views/content/en/positive-outcome.md
apps/ukvi-complaints/views/content/en/refund-premium.md
apps/ukvi-complaints/views/content/en/rules-and-guidance.md
package.json
yarn.lock

Update HOF and edit markdown files to work with the new module
The old module included in HOF contained a security vulnerability and hasn't been updated in 2 years

HOFF-162: Update HOF and fix markdown for new module

---

.drone.yml

What
Changed staging deployment env secret names to kube_server_dev and kube_token_dev 
Why
The improved pipeline changes had the names as kube_server_stg and kube_token_stg which has not been added to the preprod namespace. While a request is made to ACP this is temporary fix to deploy to preprod

Changed kube secrets to dev to deploy to preprod

---

server.js

**Changes**	
- server.js updated to include htmlLang as 'en'
- Retested using the wave tool and is now shown as correct.

UKVIC-117: The language of the document is not identified or a lang attribute value is invalid

---

apps/ukvi-complaints/fields/index.js
apps/ukvi-complaints/translations/src/en/fields.json

What?
Added 'notUrl' validation to three input fields asking for names in UKVIC. Also added error messages when the 'notUrl' validation is triggered.
Why?
These input fields are currently accepting urls.
Testing? 
Tested locally.

UKVIC-118: Add nonUrl validations to name fields

---

.snyk
apps/ukvi-complaints/views/content/en/contact-ukvi-outside.md
apps/ukvi-complaints/views/content/en/positive-outcome-outside.md
apps/ukvi-complaints/views/content/en/refund-ihs-outside.md
apps/ukvi-complaints/views/content/en/refund-priority-outside.md
apps/ukvi-complaints/views/content/en/refund-super-priority-outside.md

**What**
Removed outdated call charges, the 'Contact UK Visas and Immigration' link has the latest charges.
**Why**
The call charges were out of date.
**How**
Removed call charges in the following pages:
/application-technical-outside-uk
/application-guidance-outside-uk
/appointment-technical-outside
/questions-appointments-outside
/positive-outcome-outside
/refund-priority-outside
/refund-super-priority-outside
/refund-ihs-outside
**Test**
Tested manually.

Removed outdated call charges info as the link contains the latest charges

---

.drone.yml
server.js

Add the following CSP rules to service config
imgSrc: [
'www.google-analytics.com',
'ssl.gstatic.com',
'www.google.co.uk/ads/ga-audiences'
],
connectSrc: [
'https://www.google-analytics.com',
'https://region1.google-analytics.com',
'https://region1.analytics.google.com'
]
Support new GA analytics domain from https://region1.analytics.google.com to https://region1.google-analytics.com

UKVIC-167: add new CSP rules to service config

---

README.md
apps/ukvi-complaints/behaviours/caseworker-email.js
apps/ukvi-complaints/behaviours/customer-email.js
apps/ukvi-complaints/emails/caseworker.html
apps/ukvi-complaints/emails/customer.html
config.js
kube/app/deployment.yml

**What**
Replace the email module Nodemailer with Gov Notify 
**Why**
The hof-emailer package uses a module which contains a high vulnerability (nodemailer-smtp-transport https://www.npmjs.com/package/nodemailer-smtp-transport). This package hasn't been updated in five years so uses a vulnerable version of lodash. 
**How**
Updated the service code and config to use the hof notify component for sending caseworker and confirmation emails
**Test**
Manual testing in local, branch and UAT. Unit tests and automated tests

Replace email module with Gov Notify

---

apps/ukvi-complaints/fields/index.js
apps/ukvi-complaints/translations/src/en/fields.json
package.json
test/_features/step_definitions/steps.js
test/_features/ukvi-complaints/validation.feature

- Make field for question "What is the reference number for your complaint?" required
- Add regex validation for all reference numbers on /application-ref-numbers page
- Add relevant validation messages when refnumbers are invalid
- Add new acceptance tests for all reference number validations
Bugs raised in:
https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-218
https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-217
All unit tests + acceptances tests passing locally
Testing completed on branch environment

UKVIC-217 & 218: Reference number validations

---

package.json

[HOFF-642 ](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-642).- changing Queen's crown to King's crown logo
 
The Gov.uk crown logo changed
 
yarn install hof@20.4.0
 
Tested locally
 
 

HOFF-642 Update UKVI-C to HOF v20.4.0

---

.drone.yml

What?
I've added Trivy Scanner to Pipeline and removed deprecated Anchore Scanner for the UKVI service, see ticket
[https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-536](url)
Why?
Trivy will let you scan images, file systems and repositories for any vulnerabilities and issues. It will detect CVEs of OS packages, applications susceptibilities, and exposures of IaC in Terraform files, Kubernetes and Docker.
Drawback of Anchore Scanner is it’s significantly slower, the process of using it is more cumbersome, the output is less friendly and most importantly, it scans fewer CVEs.
See [[ukvi-complaints](https://github.com/UKHomeOffice/ukvi-complaints)](url) for more information.
How?
Removed Anchore cve exception file and added trivy cve exception file in hof-services-config repo from …

WIP -DO NOT MERGE -  HOFF-467: Replace Anchore with Trivy

---

.snyk
apps/ukvi-complaints/behaviours/customer-email.js
config.js
test/setup.js
yarn.lock

- Fix 400 notify error when no email is given - [UKVIC-230](https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-230)
- When the user chooses the existing complaint option and has a reference number, they are not required to enter an email but on submission, gov notify expects an email and throws a 400 error.
- business has provided an inbox where these types of submission emails can go. This inbox is assigned to noEmail key in the app. The noEmail key and value env has been added to config.js
- replaced invalid default noop@localhost with noEmail env in customer-email behaviour
- tested locally
- removed default values in config.js (previously agreed that where possible we should not have default values in config.js)
- added unit test envs to test/setup after removing default values …

UKVIC-230: Fix 400 notify error when no email is given

---

bin/deploy.sh

* Redis pods required to be deployed ahead of other microservices
* Many applications and services depend on Redis for caching, queuing, or session management. If Redis is deployed later, other services that rely on it might fail to start or experience downtime because they cannot access the Redis instance.
* Redis may require initialization of resources like persistent storage (which we are intending to add), replication setup, and network configurations. Deploying Redis first gives it time to initialize these resources and ensure they are ready before dependent services are started.
* Fixes Drone Pipeline issue
* rest of services are using the same order
* In deploy.sh ensure the redis deployment is added before the other deployments as seen in the commit
*
here is an [example …

UKVIC-246: Rearrange the order of kube deployments

---

apps/ukvi-complaints/translations/src/en/accessibility.json
apps/ukvi-complaints/views/accessibility.html

- removed non-compliance item that has been addressed; updated statement review date (accessibility.md)
https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-260
- removed translation for accessibility statement no longer needed
- removed HTML tag for unneeded accessibility statement
- ensure accessibility statement
- does not include mention of session timeout
- was last reviewed on 18 Mar 2025

UKVIC-260: Update accessibility statement

---

apps/ukvi-complaints/translations/src/en/fields.json

Validation error message missing on these UKVIC pages. Please see following ticket [UKVIC-254](https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-254)
Bug identified
Added the validation messages in the fields.json file
Manual testing conducted

[UKVIC 254] add missing validation messages

---

apps/ukvi-complaints/emails/customer.html

Remove the final paragraph in the email to the user after they submit the UKVIC form
https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-276

UKVIC-276: removing final paragraph of notify email template

---

bin/deploy.sh
kube/app/ingress-external.yml
kube/app/ingress-internal.yml
kube/certs/certificate-external.yml
kube/certs/certificate-internal.yml

* All the generate file vault url links are seen having cert errors
* This blocks all the tickets in Branch Env
* Issue is fixed by using same DNS pattern for File vault and external ingress. Common name/DNS used in certs are also updated.
* These changes are based on the url pattterns we use
* This issue could be from the day we implemented the amend form with file vault inclusion
* These changes need to be merged and then all feature branches should rebase with these changes to ensure fv url are working without cert issues
* Update the certs that are deployed to branch and also use the same dns pattern for file vault and external ingress of app
* Smoke test done to confirm
* Testers will run smoke and regressions tests in branch to confirm.
here is an [example …

HOFF-1291: Fix File vault certs

---

kube/redis/redis-deployment.yml

* Following changes has been done to Redis image
*  Upgraded Redis from 5.0.6 to 7.0.15 and tagged image accordingly.
*   Switched base image from Fedora to Rocky Linux 9.3 due to Trivy support.
*  Done sanity checks on UKVIC and is working as expected.
*  Refer to https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1227
* Further information added to description of Jira ticket
**Upgrading Redis to 7.0.15**
Security Fixes: Redis 5.0.6 is quite old and has known vulnerabilities. Upgrading to 7.0.15 ensures you're protected against those and benefits from the latest security patches.
Performance Improvements: Newer Redis versions often include performance optimizations and bug fixes that improve stability and efficiency.
Feature Enhancements: Redis 7.x introduces new features like ACL …

HOFF-1227: Use latest Redis Docker image with fixed vulnerabilities
