- .eslintignore
- .eslintrc
- .gitignore
- .jscsrc
- .travis.yml
- Dockerfile
- README.md
- acceptance_tests/.eslintrc
- acceptance_tests/codecept.json
- acceptance_tests/features/happy.js
- acceptance_tests/steps.js
- package.json
- run.sh
* Codecept acceptance test framework added
* Travis config file updated for Travis CI
* Docker files updated
* dotfiles updated
> UCHV-71 - Acceptance test framework integration

- acceptance_tests/.eslintrc
- acceptance_tests/codecept.conf.js
- acceptance_tests/features/applicant-name.js
- acceptance_tests/features/who.js
- acceptance_tests/pages/applicant-dob.js
- acceptance_tests/pages/applicant-name.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
* added the step field and section to the route config
* added addition skeleton steps for the personal and contact detail to the route config
* added rule to eslint in acceptance tests for generator function
* add field mixins and validation to field config
* added the field and validation translatioins
* added the acceptance tests for the step
> UCHV-62 - added the complainants step

- apps/complaints/acceptance/features/applicant-dob.js
- apps/complaints/acceptance/pages/applicant-dob.js
- apps/complaints/acceptance/pages/contact-details.js
- apps/complaints/controllers/applicant-dob.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
- apps/complaints/views/applicant-dob.html
- codecept.conf.js
- package.json
* added dob fields
* added applicant-dob controller and applicant-dob html template
* added field translations and validation / validation translation (required, numeric, numeric)
* added acceptance test for this step
* added route config
> uchv-36 - added applicant-dob step

- apps/complaints/acceptance/features/applicant-name.js
- apps/complaints/acceptance/pages/applicant-name.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
* removed extra field
* added conditional translation for app/rep
> Updated to use 1 field for name

- .gitignore
- apps/complaints/acceptance/features/contact-details.js
- apps/complaints/acceptance/pages/contact-details.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
* removed first step bypass
* added contact details step
> UCHV-34 added contact details page

- apps/complaints/acceptance/features/applicant-dob.js
- apps/complaints/acceptance/features/has-complaint-reference.js
- apps/complaints/acceptance/pages/complaint-details.js
- apps/complaints/acceptance/pages/has-complaint-reference.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
- codecept.conf.js
* added complaint reference step to routes config
* added fields and complaint reference dependent reveal
* added validation and translations
* added acceptance test for complaint reference step
* added fork to complaint type for the dob step if representative
* added acceptance test for the fork to complaint type
> uchv-50 - added previous complaint reference step

- apps/complaints/acceptance/features/complaint-details.js
- apps/complaints/acceptance/pages/complaint-details.js
- apps/complaints/acceptance/pages/summary.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/pages.json
- apps/complaints/translations/src/en/validation.json
- apps/complaints/views/complaint-details.html
- assets/scss/app.scss
- codecept.conf.js
* added complaint details step and summary step to route config
* added field and translations
* added validation
* added styling for the complaint details text-area
> uchv-69 - added complaint details step

- apps/complaints/acceptance/features/phone.js
- apps/complaints/acceptance/pages/complaint-date.js
- apps/complaints/acceptance/pages/phone.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
- assets/scss/app.scss
- codecept.conf.js
* added complaint phone number step and complaint date to route config
* added fields, validations and translations
> uchv-64 - added complaint phone number step

- apps/complaints/acceptance/features/complaint-date.js
- apps/complaints/acceptance/pages/complaint-date.js
- apps/complaints/acceptance/pages/complaint-time.js
- apps/complaints/controllers/complaint-date.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/pages.json
- apps/complaints/translations/src/en/validation.json
- apps/complaints/views/complaint-date.html
- codecept.conf.js
- test/unit/apps/complaints/controllers/complaint-date.js
* added complaint time to route config
* added fields, validations and translations for complaint date
* added controller for custom date input (allow day to be blank)
* added acceptance tests for complaint date step
* added unit tests for complaint date controller
> uchv-65 added complaint date step

- apps/complaints/acceptance/features/complaint-time.js
- apps/complaints/acceptance/pages/complaint-time.js
- apps/complaints/acceptance/pages/phoned-from.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
- codecept.conf.js
* added step to route config and phoned from step
* added fields, validation and translation
> uchv-66 - added complaint time step

- apps/complaints/acceptance/features/phoned-from.js
- apps/complaints/acceptance/pages/phoned-from.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
* added routes to config
* added field, validations and translation
> uchv-79 - added the phoned from step

- apps/complaints/acceptance/features/which-reference.js
- apps/complaints/acceptance/pages/which-reference.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
* added step to route config
* added field and validation to fields config
* added checkbox group and dependent fields
* added field translations
> uchv-80 - added reference number step

- apps/complaints/acceptance/features/premium-service-centre.js
- apps/complaints/acceptance/pages/premium-service-centre.js
- apps/complaints/fields.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/validation.json
* added step to route config
* added field and validation to fields config
* added field translations
> uchv-43 - added the premium service centre step

- apps/complaints/acceptance/features/applicant-dob.js
- apps/complaints/acceptance/features/complaint-details.js
- apps/complaints/acceptance/features/confirm.js
- apps/complaints/acceptance/features/contact-details.js
- apps/complaints/acceptance/features/representative-name.js
- apps/complaints/acceptance/pages/confirm.js
- apps/complaints/acceptance/pages/confirmation.js
- apps/complaints/confirm-step-config.js
- apps/complaints/controllers/confirm.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/buttons.json
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/pages.json
- apps/complaints/views/confirm.html
- assets/scss/app.scss
- codecept.conf.js
* refactored the steps to avoid circular forks
* added step to route config
* added summary table config and translations
* added styling for the summary table
* added confirm controller to override option translations
* added confirm view
> uchv-44 - added the review complaint step

- app.js
Reverts UKHomeOffice/UKVI-Complaints#35
> Revert "Log headers"

- apps/complaints/acceptance/features/confirmation.js
- apps/complaints/acceptance/pages/confirmation.js
- apps/complaints/index.js
- apps/complaints/translations/src/en/pages.json
- apps/complaints/views/confirmation.html
- assets/scss/app.scss
* added step to route config
* added translations
* added confirmation view and styling
> uchv-22 - added the confirmation step

- Dockerfile-acceptance
- apps/complaints/acceptance/features/confirmation.js
- apps/complaints/acceptance/pages/confirmation.js
- apps/complaints/fields.js
- config.js
- docker-compose.yml
- amend acceptance tests
- update email config for SES API transport
- copy over config and countries js in dockerfile
- explicitly omit date parts form email and confirm page
> integrate confirm controller and lates version of emailer

- apps/complaints/fields.js
- apps/complaints/translations/src/en/fields.json
- apps/complaints/translations/src/en/pages.json
- apps/complaints/views/applicant-dob.html
- apps/complaints/views/complaint-date.html
removed duplicate titles by adding visuallyhidden - these are implied as titles now
> chore - update in line with hof changes

- apps/complaints/controllers/complaint-date.js
- apps/complaints/index.js
- assets/js/index.js
- assets/scss/app.scss
- package.json
- test/unit/apps/complaints/controllers/complaint-date.js
* installed hof-bootstrap#6.0.2
* installed hof-frontend-toolkit
* updated so-acceptance
* installed eslint-config-homeoffice
* fixed broken paths
> devtask - updated UKVI to use latest hof-bootstrap

- apps/complaints/acceptance/pages/confirm.js
- apps/complaints/fields.js
- apps/complaints/translations/src/en/fields.json
* hid accept declaration field from summary table
* hid has reference number fields
* updated labels for reps name and applicant name
> amends - confirm page

- apps/complaints/acceptance/features/premium-service-centre.js
- apps/complaints/index.js
* pointed service centre next at has-reference
* updated acceptance tests
> bugfix - UCHV-92 - ref number skipped on service centre route

- apps/complaints/translations/src/en/validation.json
* added missing validation message
> bugfix - UCHV-86 DOB validation

- apps/complaints/fields.js
- apps/complaints/translations/src/en/pages.json
added title to contact details page
unhid label for email-address field
> bugfix - UCHV-103

- apps/complaints/translations/src/en/fields.json
- changed wording to relate to one reference number
> bugfix - UCHV-95 - previous complaint reference summary

- assets/scss/app.scss
* increased size of year input
> bugfix - UCHV-87 - date year input size

- apps/complaints/translations/src/en/validation.json
Updated as per service request - "Tell us your" replaced with "Enter"
> Content Amend - UCHV-85 - updated validation error messages

- apps/complaints/translations/src/en/fields.json
* added hint text to telephone field as per service request
> task UCHV-118 - added hint text

- apps/complaints/translations/src/en/pages.json
* update content on complaint step in line with service request
> Amend - UCHV-109 - content change

- apps/complaints/translations/src/en/validation.json
Updated error messages for selects, now read "select.." rather than "Enter..."
> Content - UCHV-110/UCHV-111

- apps/complaints/translations/src/en/pages.json
* added email content from ticket
> Task UCHV-99 - added email content

- apps/complaints/acceptance/features/contact-details.js
- apps/complaints/acceptance/pages/contact-details.js
- apps/complaints/fields.js
- apps/complaints/translations/src/en/validation.json
* removed numeric validator from phone number fields
* added custom validator which allows brackes, spaces, plus and hyphen chars
> bugfix - UCHV-106 - phone number validation

- apps/complaints/translations/src/en/fields.json
Amended wording of who are you question
> Amend - UCHV-99

- package.json
update to latest to make use of the changes specifically the CSP
> Update to latest version of hof-bootstrap

- app.js
- package.json
- makes use of changes to CSP that add google analytics
to list of allowed sources for js and img.
- removed unnecessay config params from app.js for `fields` and `views`.
> Updated to latest hof-bootstrap (v9.3.0)

- package.json
- This is also to deploy hof-emailer 1.6.2 to dev
- Drone it seems may require a push to master to do this
> Update to hof-controllers 6.0.3

- .gitignore
- config.js
- index.js
- package-lock.json
- package.json
What: Add in missing index.js file taken from https://github.com/Marvell-Consulting/ukvi-complaints/blob/master/index.js which looks like it wasn't copied over. Have also added a dotenv configuration as the .env file wasn't be accessed.  
Why: Ukvi-complaints is not running locally as a result of the most recent changes to the master branch.
> SD 138: Fix ukvi-complaints

- .drone.yml
**Jira Ticket**: https://collaboration.homeoffice.gov.uk/jira/browse/SD-128
**Changes:** Updated drone.yaml file to version 1
> SD-128: Update drone to version 1 

- .drone.yml
- Dockerfile
- package-lock.json
- package.json
**Jira Ticket**: https://collaboration.homeoffice.gov.uk/jira/browse/SD-725
**Changes**
* Updated image in drone pipeline build step to node:14
* Changed docker image from node:10-alpine to node:14-alpine.
* Updated package.json to include node version "14.16.1"
* Corrected Typo Error in .drone.yml file for feature branch events"
> SD-725: upgrade node version

- .drone.yml
**Jira Ticket:** https://collaboration.homeoffice.gov.uk/jira/browse/SD-725
**Changes:**
* Added tagging conditional of kube repo in drone.yml file, to enable rebuild of pipelines.
> SD-725: Added tagging conditional of kube repo in drone.yml file

- .drone.yml
- README.md
**What**
Changed _preprod_ namespace to correct name
**Why**
_Preprod_ namespace had been moved to correct project, so the namespace needed changing
> Sd 710/new preprod env

- config.js
- Adding environment variable toggle to turn on/off decs integration freature
> HOF 9 - add on/off toggle

- config.js
Change to offline/online toggling
> HOF-9-on/off-decs-sqs

- package-lock.json
What
Update nodemailer version to resolve critical severity vulnerability
Why
Improve security and reliability
How
Updated package to later version
> SD-786: update nodemailer version

- .drone.yml
- Dockerfile
- package.json
1. Upgrade node to version 14.16.1 in package.json, drone pipeline and dockerfile
2. Fix issues with build pipeline
1. Node 10 is no longer supported
2. Build pipeline was broken
> SD-725: Upgrade node to version 14

- .drone.yml
Change instances of 'master' in the pipeline to 'main' 
The default branch has been changed from 'master' to 'main'
> Update pipeline to reflect default branch change

- apps/ukvi-complaints/index.js
**What**
Removed displaying labels code from translation, in the summary/confirm page
**Why**
Error occurred in ukvi-complaints summary page as hof-behaviour-summary-page v3.3.0 now handles displaying labels from translation
**How**
Edited the code that displays summary information
**Test**
Successful unit and lint tests
> SD-994 confirm page error

- .eslintignore
- .gitignore
- apps/ukvi-complaints/behaviours/send-to-sqs.js
- apps/ukvi-complaints/fields/index.js
- apps/ukvi-complaints/index.js
- config.js
- package-lock.json
- package.json
- test/reporter-config/unit.json
- test/test-helpers.js
- test/unit/behaviours/send-to-sqs.spec.js
- test/unit/format-complaint-data.spec.js
- test/unit/json-converters/brp.spec.js
- test/unit/json-converters/complaint.spec.js
- test/unit/json-converters/decision.spec.js
- test/unit/json-converters/delays.spec.js
- test/unit/json-converters/existing.spec.js
- test/unit/json-converters/making-appointment.spec.js
- test/unit/json-converters/refund.spec.js
- test/unit/json-converters/staff-behaviour.spec.js
- test/unit/json-converters/submitting-application.spec.js
- test/unit/test-data/complaint-base.js
- test/unit/utils.spec.js
Adds unit tests for SQS work
Have also left a comment in apps/ukvi-complaints/behaviours/send-to-sqs.js behaviour
> Add tests and scripts to run them

- apps/ukvi-complaints/fields/index.js
Edit max length of a field to match the schema
> Edit max length of agent-representative-name to match schema

- apps/ukvi-complaints/behaviours/send-to-sqs.js
- package-lock.json
- package.json
**What**
Create alerts to be sent by Sysdig 
**Why**
To alert support when sending a complaint to SQS fails or succeeds
**How**
Used a StatD client to increment counters for success and fail when a send succeeds or fails.
**Test**
Create alerts on Sysdig to send alerts to the sas-support channel in slack
> Alerts for send to SQS success and fail

- .drone.yml
- kube/app/deployment.yml
- lib/json-converters/delays.js
What
Added the answer to the webform question "When did you submit your application?" To the message sent to SQS
Why
Information entered for webform question "When did you submit your application?" is not visible in DECS
How
Updated the SQS complaint message to include the missing info.
Test
Submit a ‘Waiting for a decision or documents’ complaint and check on DECS if the ‘When did you submit your application?’ Info is present
> Corrected missing text for DECS

- .snyk
- kube/app/deployment.yml
- package.json
- yarn.lock
What
Added deployment config for DECS SQS in prod
Why
Added the required config for UKVIC to send complaints to the DECS SQS in prod. At the moment the SQS in prod is same as that used for staging. This may change in the future.
How
Updated deployment.yml with SQS details for the production env.
Test
Manual end to end test post deployment in staging
> Updated deployment config for DECS SQS in prod

- kube/app/deployment.yml
- package.json
- yarn.lock
What
Changed the name of the prod DECS SQS from the staging name to new SQS created for prod
Why
To send complaints to the DECS SQS in prod
How
Changed the name in deployment.yml
Test
Selected tests in live
> Changed Prod SQS name

- kube/app/deployment.yml
Point the staging(pre-prod) env to the prod SQS cs-prod-case-creator-sqs to test the queue
> Point staging to prod queue for testing the queue

- .snyk
- README.md
- apps/ukvi-complaints/index.js
What
Corrected confirmation page change link navigation
Why
Confirmation page change links were navigating to page not found
How
Updated the complete section
> Corrected confirmation page change link navigation

- README.md
What
Turn on send to queue for production env 
Why
To start ending complains to DECS SQS in prod
How
Set config value SEND_TO_DECS_QUEUE for prod to online
> Corrected readme and turned on send to prod queue

- apps/ukvi-complaints/views/content/en/refund-less-than.md
- yarn.lock
Amend formatting on refund journey
To correct markup issue where hashes appeared at the beginning of statement on the page
Removed hashes from beginning of statement.
Tested locally
> UKVIC-161: amend formatting on refund journey

- package.json
- yarn.lock
Updated HOF to fix snyk vulnerability
> Updated HOF to fix snyk vuln

- .drone.yml
- kube/app/deployment.yml
What
Change the name of the SQS test environment secret
Why
DECS created a new test environment
How
Changed the secret name for UAT and Branch
Test
Manual testing in branch
> Change the name of the SQS test environment secret

- apps/ukvi-complaints/fields/index.js
- apps/ukvi-complaints/translations/src/en/journey.json
- apps/ukvi-complaints/translations/src/en/pages.json
- apps/ukvi-complaints/views/confirmation.html
- assets/scss/app.scss
- package.json
- server.js
- yarn.lock
**What** 
Updated to latest GOV.UK design
**Why** 
Service was using an old version of gov uk
**How**
 Upgraded hof and fix missing header and Beta label
**Test** 
Manual testing in local
> Updated to latest GOV.UK design

- .drone.yml
WHAT?
*  Some Url's were removed by Adi
* A deployment is being made to implement these changes
*WHY?
the following url's were removed. deployment made to implement changes: 
* UKVI complaints UAT: dev.notprod.ukvi-complaints.homeoffice.gov.uk
* UKVI Complains Stage: www.preprod.notprod.ukvi-complaints.homeoffice.gov.uk
* deploying to implement changes
*WHY?
* To implement the changes
> FF-752: Deployment to Implement changes

- .drone.yml
- .snyk
WHAT?
* Deployed whitelisted IP's 
* Updated conditions so pipeline can run when on push and PR
* Fixed pipeline secrets, robots and code
*WHY? 
* To prevent public access 
the following url's were removed. deployment made to implement changes:
* UKVI complaints UAT: dev.notprod.ukvi-complaints.homeoffice.gov.uk
* UKVI Complains Stage: [www.preprod.notprod.ukvi-complaints.homeoffice.gov.uk](http://www.preprod.notprod.ukvi-complaints.homeoffice.gov.uk/)
* deploying to implement changes
> updated drone conditions

- .drone.yml
- .snyk
fixed a typo
could affect pipeline run
> Hoff 752 typo fix

- README.md
- kube/app/ingress-external.yml
[HOFF-1062](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1062) 
So we can whitelist with EBSA to access CTF
By adding and ext ingress
Deployment and adding manual IP to ensure we can access the ext url
> HOFF-1062 - Adding ext ingress to service 

- bin/deploy.sh
- kube/app/ingress-external.yml
Fixing URL for UAT typo
UAT ingress failure
Change typo
Deploy to uat
> hotfix - fix typo on uat

- .drone.yml
- .snyk
- apps/ukvi-complaints/fields/index.js
- apps/ukvi-complaints/translations/src/en/fields.json
- removed validation checking to ensure applicants are over 18
- updated snyk policy file 
- addressed linting issue
- acceptance tests optional
https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-235
- removed 18+ requirement for applicant DOB (fields.json)
- updated snyk policy file (.snyk)
- addressed linting issue (removed unused variable declaration) (fields/index.js)
- updated drone builds so acceptance tests will not cause build to fail if they do not pass (.drone.yml)
> UKVIC-235: DOB Validation

- .drone.yml
- .snyk
- apps/ukvi-complaints/index.js
Updated page to which user navigates when declares has reference number.  
https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-238
Updated `next` property for `/complaint-reference-number` (in apps/ukvi-complaints/index.js)
I have confirmed no updates are required in the email template sent to the user on confirming data submitted.  
> UKVIC-238: Details for existing complaint

- .snyk
- apps/ukvi-complaints/fields/index.js
- apps/ukvi-complaints/translations/src/en/fields.json
Following https://github.com/UKHomeOffice/ukvi-complaints/pull/286, this PR 
1.  adds validation updates the error message presented to the user if they enter a date prior to 01 01 1900; and
2. adds a validation check against dates in the future (ie: only dates  including the present day or in the past are permitted).  Users will not be permitted to continue from the page if it does not meet this criteria.  
3. updates the snyk policy file
https://collaboration.homeoffice.gov.uk/jira/browse/UKVIC-235
- the following changes have been made in `fields.json` for both `/applicant-dob` and `/agent-representative-dob`:  
- added:  the `before` validation check against dates of birth that are in the future (index.js; fields.json)
- updated:  the `after` validation check error message for dates …
> UKVIC-235 DOB validation, future check
